angleMode = "radians"; //use radians not degrees
var globalX = 0;
var globalY = 0;
var inBattle = false;
var playing = false;
var keyArray = []; //array of keys being pressed
var speed =2;
var pokemen=[];
var wild = true;
var healAnimation = false;
var dead = false;
var insideHouse = false;
var colorMod = 255;
var introSceneRequired = false;