angleMode = "radians"; //use radians not degrees
var globalX = 0;
var globalY = 0;
var inBattle = true;
var playing = false;
var keyArray = []; //array of keys being pressed
var speed =2;
var pokemen=[];
var wild = false;
var healAnimation = false;
var dead = false;
var insideHouse = false;
var insideGym = false;
var colorMod = 255;
var removeUVAPokeball = false;
var changeGymPokeballColor = false;
var talkingToEnemy = false;
var fightBoss = false;
var menuUp = false;
var switchMenu = false;
var switchPokemon = false;
var throwPokeball = false;
var pokeballMenu = false;
var chosen=0;
var openEndGamePokeball = false;
var showCredits = false;

var introSceneRequired = false;
var defeatedTrainer = false;